-- Users (Supports both authenticated users and guests)
CREATE TABLE users (
    id UUID PRIMARY KEY, -- generated by client or server
    email VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Main Categories (Mood, Hustle, Relationship, Occasion, Deep, Source)
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT
);

-- Subcategories (Melancholy, Uplifting, etc.)
CREATE TABLE subcategories (
    id SERIAL PRIMARY KEY,
    category_id INTEGER REFERENCES categories(id),
    name VARCHAR(50) NOT NULL,
    tags TEXT[] -- Keywords for search/matching
);

-- Quotes
CREATE TABLE quotes (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    author VARCHAR(100) DEFAULT 'Unknown',
    subcategory_id INTEGER REFERENCES subcategories(id),
    background_color VARCHAR(50) DEFAULT '#e0e5ec',
    text_color VARCHAR(50) DEFAULT '#334155',
    font_family VARCHAR(50) DEFAULT 'Inter, sans-serif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User Interactions for the Smart System
CREATE TABLE user_interactions (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    quote_id INTEGER REFERENCES quotes(id),
    interaction_type VARCHAR(20) NOT NULL, -- 'view', 'like', 'remix', 'share'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
-- CREATE INDEX idx_interactions_user ON user_interactions(user_id);
-- CREATE INDEX idx_quotes_subcategory ON quotes(subcategory_id);
